number1 = int(input('enter number1: '))
number2 = int(input('enter number2: '))
number3 = int(input('enter number3: '))
print('The sum of integers is equal to', number1 + number2 + number3)
print('The product of integers is equal to', number1 * number2 * number3)
print('The average is', (number1 + number2 + number3) / 3)
print('The biggest integer is', max(number1, number2, number3), 'while the smallest integer is', min(number1, number2, number3))
